(!window.console||!console.log)&&function(){for(var d=function(){},g="assert,clear,count,debug,dir,dirxml,error,exception,group,groupCollapsed,groupEnd,info,log,markTimeline,profile,profileEnd,markTimeline,table,time,timeEnd,timeStamp,trace,warn".split(","),i=g.length,a=window.console={};i--;)a[g[i]]=d}();
(function(d){d.fn.fitVids=function(g){var i={customSelector:null},a=document.createElement("div"),c=document.getElementsByTagName("base")[0]||document.getElementsByTagName("script")[0];a.className="fit-vids-style";a.innerHTML="&shy;<style>               .fluid-width-video-wrapper {                 width: 100%;                              position: relative;                       padding: 0;                            }                                                                                   .fluid-width-video-wrapper iframe,        .fluid-width-video-wrapper object,        .fluid-width-video-wrapper embed {           position: absolute;                       top: 0;                                   left: 0;                                  width: 100%;                              height: 100%;                          }                                       </style>";
c.parentNode.insertBefore(a,c);g&&d.extend(i,g);return this.each(function(){var a=["iframe[src*='player.vimeo.com']","iframe[src*='www.youtube.com']","iframe[src*='www.kickstarter.com']","object","embed"];i.customSelector&&a.push(i.customSelector);d(this).find(a.join(",")).each(function(){var a=d(this);if(!(this.tagName.toLowerCase()=="embed"&&a.parent("object").length||a.parent(".fluid-width-video-wrapper").length)){var c=(this.tagName.toLowerCase()=="object"?a.attr("height"):a.height())/a.width();
if(!a.attr("id")){var e="fitvid"+Math.floor(Math.random()*999999);a.attr("id",e)}a.wrap('<div class="fluid-width-video-wrapper"></div>').parent(".fluid-width-video-wrapper").css("padding-top",c*100+"%");a.removeAttr("height").removeAttr("width")}})})}})(jQuery);
(function(d){d.flexslider=function(g,i){var a=d(g),c=d.extend({},d.flexslider.defaults,i),e=c.namespace,p="ontouchstart"in window||window.DocumentTouch&&document instanceof DocumentTouch,s=p?"touchend":"click",m=c.direction==="vertical",l=c.reverse,j=c.itemWidth>0,q=c.animation==="fade",o=c.asNavFor!=="",f={};d.data(g,"flexslider",a);f={init:function(){a.animating=!1;a.currentSlide=c.startAt;a.animatingTo=a.currentSlide;a.atEnd=a.currentSlide===0||a.currentSlide===a.last;a.containerSelector=c.selector.substr(0,
c.selector.search(" "));a.slides=d(c.selector,a);a.container=d(a.containerSelector,a);a.count=a.slides.length;a.syncExists=d(c.sync).length>0;if(c.animation==="slide")c.animation="swing";a.prop=m?"top":"marginLeft";a.args={};a.manualPause=!1;a.transitions=!c.video&&!q&&c.useCSS&&function(){var b=document.createElement("div"),c=["perspectiveProperty","WebkitPerspective","MozPerspective","OPerspective","msPerspective"],d;for(d in c)if(b.style[c[d]]!==void 0)return a.pfx=c[d].replace("Perspective","").toLowerCase(),
a.prop="-"+a.pfx+"-transform",!0;return!1}();if(c.controlsContainer!=="")a.controlsContainer=d(c.controlsContainer).length>0&&d(c.controlsContainer);if(c.manualControls!=="")a.manualControls=d(c.manualControls).length>0&&d(c.manualControls);c.randomize&&(a.slides.sort(function(){return Math.round(Math.random())-0.5}),a.container.empty().append(a.slides));a.doMath();o&&f.asNav.setup();a.setup("init");c.controlNav&&f.controlNav.setup();c.directionNav&&f.directionNav.setup();c.keyboard&&(d(a.containerSelector).length===
1||c.multipleKeyboard)&&d(document).bind("keyup",function(b){b=b.keyCode;if(!a.animating&&(b===39||b===37))b=b===39?a.getTarget("next"):b===37?a.getTarget("prev"):!1,a.flexAnimate(b,c.pauseOnAction)});c.mousewheel&&a.bind("mousewheel",function(b,h){b.preventDefault();var d=h<0?a.getTarget("next"):a.getTarget("prev");a.flexAnimate(d,c.pauseOnAction)});c.pausePlay&&f.pausePlay.setup();c.slideshow&&(c.pauseOnHover&&a.hover(function(){!a.manualPlay&&!a.manualPause&&a.pause()},function(){!a.manualPause&&
!a.manualPlay&&a.play()}),c.initDelay>0?setTimeout(a.play,c.initDelay):a.play());p&&c.touch&&f.touch();(!q||q&&c.smoothHeight)&&d(window).bind("resize focus",f.resize);setTimeout(function(){c.start(a)},200)},asNav:{setup:function(){a.asNav=!0;a.animatingTo=Math.floor(a.currentSlide/a.move);a.currentItem=a.currentSlide;a.slides.removeClass(e+"active-slide").eq(a.currentItem).addClass(e+"active-slide");a.slides.click(function(b){b.preventDefault();var b=d(this),h=b.index();if(!d(c.asNavFor).data("flexslider").animating&&
!b.hasClass("active"))a.direction=a.currentItem<h?"next":"prev",a.flexAnimate(h,c.pauseOnAction,!1,!0,!0)})}},controlNav:{setup:function(){a.manualControls?f.controlNav.setupManual():f.controlNav.setupPaging()},setupPaging:function(){var b=1,h;a.controlNavScaffold=d('<ol class="'+e+"control-nav "+e+(c.controlNav==="thumbnails"?"control-thumbs":"control-paging")+'"></ol>');if(a.pagingCount>1)for(var r=0;r<a.pagingCount;r++)h=c.controlNav==="thumbnails"?'<img src="'+a.slides.eq(r).attr("data-thumb")+
'"/>':"<a>"+b+"</a>",a.controlNavScaffold.append("<li>"+h+"</li>"),b++;a.controlsContainer?d(a.controlsContainer).append(a.controlNavScaffold):a.append(a.controlNavScaffold);f.controlNav.set();f.controlNav.active();a.controlNavScaffold.delegate("a, img",s,function(b){b.preventDefault();var b=d(this),h=a.controlNav.index(b);if(!b.hasClass(e+"active"))a.direction=h>a.currentSlide?"next":"prev",a.flexAnimate(h,c.pauseOnAction)});p&&a.controlNavScaffold.delegate("a","click touchstart",function(a){a.preventDefault()})},
setupManual:function(){a.controlNav=a.manualControls;f.controlNav.active();a.controlNav.live(s,function(b){b.preventDefault();var b=d(this),h=a.controlNav.index(b);if(!b.hasClass(e+"active"))h>a.currentSlide?a.direction="next":a.direction="prev",a.flexAnimate(h,c.pauseOnAction)});p&&a.controlNav.live("click touchstart",function(a){a.preventDefault()})},set:function(){a.controlNav=d("."+e+"control-nav li "+(c.controlNav==="thumbnails"?"img":"a"),a.controlsContainer?a.controlsContainer:a)},active:function(){a.controlNav.removeClass(e+
"active").eq(a.animatingTo).addClass(e+"active")},update:function(b,c){a.pagingCount>1&&b==="add"?a.controlNavScaffold.append(d("<li><a>"+a.count+"</a></li>")):a.pagingCount===1?a.controlNavScaffold.find("li").remove():a.controlNav.eq(c).closest("li").remove();f.controlNav.set();a.pagingCount>1&&a.pagingCount!==a.controlNav.length?a.update(c,b):f.controlNav.active()}},directionNav:{setup:function(){var b=d('<ul class="'+e+'direction-nav"><li><a class="'+e+'prev" href="#">'+c.prevText+'</a></li><li><a class="'+
e+'next" href="#">'+c.nextText+"</a></li></ul>");a.controlsContainer?(d(a.controlsContainer).append(b),a.directionNav=d("."+e+"direction-nav li a",a.controlsContainer)):(a.append(b),a.directionNav=d("."+e+"direction-nav li a",a));f.directionNav.update();a.directionNav.bind(s,function(b){b.preventDefault();b=d(this).hasClass(e+"next")?a.getTarget("next"):a.getTarget("prev");a.flexAnimate(b,c.pauseOnAction)});p&&a.directionNav.bind("click touchstart",function(a){a.preventDefault()})},update:function(){var b=
e+"disabled";a.pagingCount===1?a.directionNav.addClass(b):c.animationLoop?a.directionNav.removeClass(b):a.animatingTo===0?a.directionNav.removeClass(b).filter("."+e+"prev").addClass(b):a.animatingTo===a.last?a.directionNav.removeClass(b).filter("."+e+"next").addClass(b):a.directionNav.removeClass(b)}},pausePlay:{setup:function(){var b=d('<div class="'+e+'pauseplay"><a></a></div>');a.controlsContainer?(a.controlsContainer.append(b),a.pausePlay=d("."+e+"pauseplay a",a.controlsContainer)):(a.append(b),
a.pausePlay=d("."+e+"pauseplay a",a));f.pausePlay.update(c.slideshow?e+"pause":e+"play");a.pausePlay.bind(s,function(b){b.preventDefault();d(this).hasClass(e+"pause")?(a.manualPause=!0,a.manualPlay=!1,a.pause()):(a.manualPause=!1,a.manualPlay=!0,a.play())});p&&a.pausePlay.bind("click touchstart",function(a){a.preventDefault()})},update:function(b){b==="play"?a.pausePlay.removeClass(e+"pause").addClass(e+"play").text(c.playText):a.pausePlay.removeClass(e+"play").addClass(e+"pause").text(c.pauseText)}},
touch:function(){function b(b){k=m?e-b.touches[0].pageY:e-b.touches[0].pageX;p=m?Math.abs(k)<Math.abs(b.touches[0].pageX-f):Math.abs(k)<Math.abs(b.touches[0].pageY-f);if(!p||Number(new Date)-o>500)b.preventDefault(),!q&&a.transitions&&(c.animationLoop||(k/=a.currentSlide===0&&k<0||a.currentSlide===a.last&&k>0?Math.abs(k)/n+2:1),a.setProps(i+k,"setTouch"))}function d(){if(a.animatingTo===a.currentSlide&&!p&&k!==null){var j=l?-k:k,m=j>0?a.getTarget("next"):a.getTarget("prev");a.canAdvance(m)&&(Number(new Date)-
o<550&&Math.abs(j)>50||Math.abs(j)>n/2)?a.flexAnimate(m,c.pauseOnAction):a.flexAnimate(a.currentSlide,c.pauseOnAction,!0)}g.removeEventListener("touchmove",b,!1);g.removeEventListener("touchend",d,!1);i=k=f=e=null}var e,f,i,n,k,o,p=!1;g.addEventListener("touchstart",function(k){a.animating?k.preventDefault():k.touches.length===1&&(a.pause(),n=m?a.h:a.w,o=Number(new Date),i=j&&l&&a.animatingTo===a.last?0:j&&l?a.limit-(a.itemW+c.itemMargin)*a.move*a.animatingTo:j&&a.currentSlide===a.last?a.limit:j?
(a.itemW+c.itemMargin)*a.move*a.currentSlide:l?(a.last-a.currentSlide+a.cloneOffset)*n:(a.currentSlide+a.cloneOffset)*n,e=m?k.touches[0].pageY:k.touches[0].pageX,f=m?k.touches[0].pageX:k.touches[0].pageY,g.addEventListener("touchmove",b,!1),g.addEventListener("touchend",d,!1))},!1)},resize:function(){!a.animating&&a.is(":visible")&&(j||a.doMath(),q?f.smoothHeight():j?(a.slides.width(a.computedW),a.update(a.pagingCount),a.setProps()):m?(a.viewport.height(a.h),a.setProps(a.h,"setTotal")):(c.smoothHeight&&
f.smoothHeight(),a.newSlides.width(a.computedW),a.setProps(a.computedW,"setTotal")))},smoothHeight:function(b){if(!m||q){var c=q?a:a.viewport;b?c.animate({height:a.slides.eq(a.animatingTo).height()},b):c.height(a.slides.eq(a.animatingTo).height())}},sync:function(b){var h=d(c.sync).data("flexslider"),e=a.animatingTo;switch(b){case "animate":h.flexAnimate(e,c.pauseOnAction,!1,!0);break;case "play":!h.playing&&!h.asNav&&h.play();break;case "pause":h.pause()}}};a.flexAnimate=function(b,h,r,g,i){if(o&&
a.pagingCount===1)a.direction=a.currentItem<b?"next":"prev";if(!a.animating&&(a.canAdvance(b,i)||r)&&a.is(":visible")){if(o&&g)if(r=d(c.asNavFor).data("flexslider"),a.atEnd=b===0||b===a.count-1,r.flexAnimate(b,!0,!1,!0,i),a.direction=a.currentItem<b?"next":"prev",r.direction=a.direction,Math.ceil((b+1)/a.visible)-1!==a.currentSlide&&b!==0)a.currentItem=b,a.slides.removeClass(e+"active-slide").eq(b).addClass(e+"active-slide"),b=Math.floor(b/a.visible);else return a.currentItem=b,a.slides.removeClass(e+
"active-slide").eq(b).addClass(e+"active-slide"),!1;a.animating=!0;a.animatingTo=b;c.before(a);h&&a.pause();a.syncExists&&!i&&f.sync("animate");c.controlNav&&f.controlNav.active();j||a.slides.removeClass(e+"active-slide").eq(b).addClass(e+"active-slide");a.atEnd=b===0||b===a.last;c.directionNav&&f.directionNav.update();b===a.last&&(c.end(a),c.animationLoop||a.pause());if(q)a.slides.eq(a.currentSlide).fadeOut(c.animationSpeed,c.easing),a.slides.eq(b).fadeIn(c.animationSpeed,c.easing,a.wrapup);else{var n=
m?a.slides.filter(":first").height():a.computedW;j?(b=c.itemWidth>a.w?c.itemMargin*2:c.itemMargin,b=(a.itemW+b)*a.move*a.animatingTo,b=b>a.limit&&a.visible!==1?a.limit:b):b=a.currentSlide===0&&b===a.count-1&&c.animationLoop&&a.direction!=="next"?l?(a.count+a.cloneOffset)*n:0:a.currentSlide===a.last&&b===0&&c.animationLoop&&a.direction!=="prev"?l?0:(a.count+1)*n:l?(a.count-1-b+a.cloneOffset)*n:(b+a.cloneOffset)*n;a.setProps(b,"",c.animationSpeed);if(a.transitions){if(!c.animationLoop||!a.atEnd)a.animating=
!1,a.currentSlide=a.animatingTo;a.container.unbind("webkitTransitionEnd transitionend");a.container.bind("webkitTransitionEnd transitionend",function(){a.wrapup(n)})}else a.container.animate(a.args,c.animationSpeed,c.easing,function(){a.wrapup(n)})}c.smoothHeight&&f.smoothHeight(c.animationSpeed)}};a.wrapup=function(b){!q&&!j&&(a.currentSlide===0&&a.animatingTo===a.last&&c.animationLoop?a.setProps(b,"jumpEnd"):a.currentSlide===a.last&&a.animatingTo===0&&c.animationLoop&&a.setProps(b,"jumpStart"));
a.animating=!1;a.currentSlide=a.animatingTo;c.after(a)};a.animateSlides=function(){a.animating||a.flexAnimate(a.getTarget("next"))};a.pause=function(){clearInterval(a.animatedSlides);a.playing=!1;c.pausePlay&&f.pausePlay.update("play");a.syncExists&&f.sync("pause")};a.play=function(){a.animatedSlides=setInterval(a.animateSlides,c.slideshowSpeed);a.playing=!0;c.pausePlay&&f.pausePlay.update("pause");a.syncExists&&f.sync("play")};a.canAdvance=function(b,d){var e=o?a.pagingCount-1:a.last;return d?!0:
o&&a.currentItem===a.count-1&&b===0&&a.direction==="prev"?!0:o&&a.currentItem===0&&b===a.pagingCount-1&&a.direction!=="next"?!1:b===a.currentSlide&&!o?!1:c.animationLoop?!0:a.atEnd&&a.currentSlide===0&&b===e&&a.direction!=="next"?!1:a.atEnd&&a.currentSlide===e&&b===0&&a.direction==="next"?!1:!0};a.getTarget=function(b){a.direction=b;return b==="next"?a.currentSlide===a.last?0:a.currentSlide+1:a.currentSlide===0?a.last:a.currentSlide-1};a.setProps=function(b,d,e){var f=function(){var e=b?b:(a.itemW+
c.itemMargin)*a.move*a.animatingTo;return function(){if(j)return d==="setTouch"?b:l&&a.animatingTo===a.last?0:l?a.limit-(a.itemW+c.itemMargin)*a.move*a.animatingTo:a.animatingTo===a.last?a.limit:e;else switch(d){case "setTotal":return l?(a.count-1-a.currentSlide+a.cloneOffset)*b:(a.currentSlide+a.cloneOffset)*b;case "setTouch":return l?b:b;case "jumpEnd":return l?b:a.count*b;case "jumpStart":return l?a.count*b:b;default:return b}}()*-1+"px"}();a.transitions&&(f=m?"translate3d(0,"+f+",0)":"translate3d("+
f+",0,0)",e=e!==void 0?e/1E3+"s":"0s",a.container.css("-"+a.pfx+"-transition-duration",e));a.args[a.prop]=f;(a.transitions||e===void 0)&&a.container.css(a.args)};a.setup=function(b){if(q)a.slides.css({width:"100%","float":"left",marginRight:"-100%",position:"relative"}),b==="init"&&a.slides.eq(a.currentSlide).fadeIn(c.animationSpeed,c.easing),c.smoothHeight&&f.smoothHeight();else{var h,g;if(b==="init"&&(a.viewport=d('<div class="'+e+'viewport"></div>').css({overflow:"hidden",position:"relative"}).appendTo(a).append(a.container),
a.cloneCount=0,a.cloneOffset=0,l))g=d.makeArray(a.slides).reverse(),a.slides=d(g),a.container.empty().append(a.slides);if(c.animationLoop&&!j)a.cloneCount=2,a.cloneOffset=1,b!=="init"&&a.container.find(".clone").remove(),a.container.append(a.slides.first().clone().addClass("clone")).prepend(a.slides.last().clone().addClass("clone"));a.newSlides=d(c.selector,a);h=l?a.count-1-a.currentSlide+a.cloneOffset:a.currentSlide+a.cloneOffset;m&&!j?(a.container.height((a.count+a.cloneCount)*200+"%").css("position",
"absolute").width("100%"),setTimeout(function(){a.newSlides.css({display:"block"});a.doMath();a.viewport.height(a.h);a.setProps(h*a.h,"init")},b==="init"?100:0)):(a.container.width((a.count+a.cloneCount)*200+"%"),a.setProps(h*a.computedW,"init"),setTimeout(function(){a.doMath();a.newSlides.css({width:a.computedW,"float":"left",display:"block"});c.smoothHeight&&f.smoothHeight()},b==="init"?100:0))}j||a.slides.removeClass(e+"active-slide").eq(a.currentSlide).addClass(e+"active-slide")};a.doMath=function(){var b=
a.slides.first(),d=c.itemMargin,e=c.minItems,f=c.maxItems;a.w=a.width();a.h=b.height();a.boxPadding=b.outerWidth()-b.width();j?(a.itemT=c.itemWidth+d,a.minW=e?e*a.itemT:a.w,a.maxW=f?f*a.itemT:a.w,a.itemW=a.minW>a.w?(a.w-d*e)/e:a.maxW<a.w?(a.w-d*f)/f:c.itemWidth>a.w?a.w:c.itemWidth,a.visible=Math.floor(a.w/(a.itemW+d)),a.move=c.move>0&&c.move<a.visible?c.move:a.visible,a.pagingCount=Math.ceil((a.count-a.visible)/a.move+1),a.last=a.pagingCount-1,a.limit=a.pagingCount===1?0:c.itemWidth>a.w?(a.itemW+
d*2)*a.count-a.w-d:(a.itemW+d)*a.count-a.w-d):(a.itemW=a.w,a.pagingCount=a.count,a.last=a.count-1);a.computedW=a.itemW-a.boxPadding};a.update=function(b,d){a.doMath();if(!j)b<a.currentSlide?a.currentSlide+=1:b<=a.currentSlide&&b!==0&&(a.currentSlide-=1),a.animatingTo=a.currentSlide;if(c.controlNav&&!a.manualControls)if(d==="add"&&!j||a.pagingCount>a.controlNav.length)f.controlNav.update("add");else if(d==="remove"&&!j||a.pagingCount<a.controlNav.length)j&&a.currentSlide>a.last&&(a.currentSlide-=1,
a.animatingTo-=1),f.controlNav.update("remove",a.last);c.directionNav&&f.directionNav.update()};a.addSlide=function(b,e){var f=d(b);a.count+=1;a.last=a.count-1;m&&l?e!==void 0?a.slides.eq(a.count-e).after(f):a.container.prepend(f):e!==void 0?a.slides.eq(e).before(f):a.container.append(f);a.update(e,"add");a.slides=d(c.selector+":not(.clone)",a);a.setup();c.added(a)};a.removeSlide=function(b){var e=isNaN(b)?a.slides.index(d(b)):b;a.count-=1;a.last=a.count-1;isNaN(b)?d(b,a.slides).remove():m&&l?a.slides.eq(a.last).remove():
a.slides.eq(b).remove();a.doMath();a.update(e,"remove");a.slides=d(c.selector+":not(.clone)",a);a.setup();c.removed(a)};f.init()};d.flexslider.defaults={namespace:"flex-",selector:".slides > li",animation:"fade",easing:"swing",direction:"horizontal",reverse:!1,animationLoop:!0,smoothHeight:!1,startAt:0,slideshow:!0,slideshowSpeed:3E3,animationSpeed:600,initDelay:0,randomize:!1,pauseOnAction:!0,pauseOnHover:!1,useCSS:!0,touch:!0,video:!1,controlNav:!1,directionNav:!1,prevText:"Previous",nextText:"Next",
keyboard:!0,multipleKeyboard:!1,mousewheel:!1,pausePlay:!1,pauseText:"Pause",playText:"Play",controlsContainer:"",manualControls:"",sync:"",asNavFor:"",itemWidth:0,itemMargin:0,minItems:0,maxItems:0,move:0,start:function(){},before:function(){},after:function(){},end:function(){},added:function(){},removed:function(){}};d.fn.flexslider=function(g){g===void 0&&(g={});if(typeof g==="object")return this.each(function(){var a=d(this),c=a.find(g.selector?g.selector:".slides > li");c.length===1?(c.fadeIn(400),
g.start&&g.start(a)):a.data("flexslider")===void 0&&new d.flexslider(this,g)});else{var i=d(this).data("flexslider");switch(g){case "play":i.play();break;case "pause":i.pause();break;case "next":i.flexAnimate(i.getTarget("next"),!0);break;case "prev":case "previous":i.flexAnimate(i.getTarget("prev"),!0);break;default:typeof g==="number"&&i.flexAnimate(g,!0)}}}})(jQuery);
